### ISSUE TITLE
Memory question

### ISSUE THREAD

**Issue by foudfou** [josehu07/hux-kernel#5]
Hi there, thank you so much as I'm learning a lot from your project! I am currently tackling paging.

I have a question about this line https://github.com/josehu07/hux-kernel/blob/7fea5c5db56fd89f6437eef843da6c6dc9e09e13/src/memory/paging.c#L52

Something I'm not sure to understand is: while `kheap_curr` is initialized to a page-aligned *memory address* right after the kernel, which itself is loaded to 1MiB, we compare `kheap_curr` to something that looks like a *quantity*:
```C
#define KMEM_MAX 0x00800000     /** 8MiB reserved for the kernel. */
```
In practice,  `KMEM_MAX` is used as an *address*, and the comment should read something like: `/* Max address reserved for the kernel */`.

What am I missing?

**Comment by josehu07** [comment]
Hi there, thanks for asking.

Yes, your understanding is correct. 8MiB is the max address reserved for kernel stuff. The comment should read `up to 8MiB reserved for the kernel`.

The amount of available memory for kernel heap and slabs will be less than 8MiB.
